-- DDL - Criar banco e tabelas

-- Criar um banco de dados
CREATE DATABASE Exercicio_1_2;

-- Usar o banco criado
USE Exercicio_1_2;

-- Criar tabelas do banco
CREATE TABLE Empresa (
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(30) NOT NULL UNIQUE,
	CNPJ VARCHAR(14) NOT NULL UNIQUE,
);

CREATE TABLE Cliente (
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
);

CREATE TABLE Marca (
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(40) NOT NULL UNIQUE,
);

CREATE TABLE Modelo (
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(30) NOT NULL,
);

CREATE TABLE Veiculo (
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	Placa VARCHAR(7) NOT NULL UNIQUE,
);

CREATE TABLE Aluguel (
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	Protocolo VARCHAR(20) NOT NULL,
	DataInicio DATE NOT NULL,
	DataFim DATE NOT NULL,
);
